name: ProjCompBio
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_3
  - libexpat=2.7.3=h885b0b7_3
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyh0d26453_0
  - python=3.14.1=h3bc0a5a_100_cp314
  - python_abi=3.14=2_cp314
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - alembic==1.17.2
      - anyascii==0.3.3
      - asttokens==3.0.1
      - click==8.3.1
      - colorama==0.4.6
      - colorlog==6.10.1
      - comm==0.2.3
      - contourpy==1.3.3
      - contractions==0.1.73
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - emoji==2.15.0
      - executing==2.2.1
      - filelock==3.20.0
      - fonttools==4.61.0
      - fsspec==2025.12.0
      - greenlet==3.3.0
      - ipykernel==7.1.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - mako==1.3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.6
      - nltk==3.9.2
      - numpy==2.3.5
      - optuna==4.6.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pillow==12.0.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - pure-eval==0.2.3
      - pyahocorasick==2.2.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2025.11.3
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - setuptools==70.2.0
      - six==1.17.0
      - sqlalchemy==2.0.45
      - stack-data==0.6.3
      - sympy==1.14.0
      - textsearch==0.0.24
      - threadpoolctl==3.6.0
      - torch==2.9.1+cu126
      - torchvision==0.24.1+cu126
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - wcwidth==0.2.14
      - wordcloud==1.9.4
      - xgboost==3.1.2
prefix: C:\Users\Austin\miniconda3\envs\ProjCompBio
